
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - Docs/Screenshots

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - Docs/Screenshots

jobs:
  - job: build_components
    displayName: Build platform component libraries
    pool:
      vmImage: 'macos-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.x'
      inputs:
        versionSpec: 5.x
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
    - bash: |
        chmod +x build.sh
        ./build.sh --target=externals
      workingDirectory: Build
      displayName: 'Build pod framework'
    - bash: |
        chmod +x buildandpack.sh
        ./buildandpack.sh
      displayName: 'Build and Generate packages'
    - task: CopyFiles@2
      displayName: 'Copy NuGet Package Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '*.nupkg'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: package'
      inputs:
        ArtifactName: package
